### ISSUE TITLE
Agree upon a name for the MongoDB implementation. 

### ISSUE THREAD

**Issue by skaclmbr** [nmtarr/NCBA#13]
Add suggestions as comments

**Comment by jpccarpenter** [comment]
- Nuthatch
- Hatch
- Teakettle
- Hallux
- Barb

**Comment by nmtarr** [comment]
- NCBAdb
- Margo

**Comment by skaclmbr** [comment]
- MongoBirdy
- MonGoBirding
- MonGoshawk
- The Trove
