### ISSUE TITLE
Add month range widget on block page.

### ISSUE THREAD

**Issue by skaclmbr** [nmtarr/NCBA#35]
Examples to encompass:
- 3 to 8 (
- 9 to 2 (i.e., Sep to Feb)

- [ ] Add widget to filter data
- [x] consider buttons for populating with Breeding, Wintering

**Comment by skaclmbr** [comment]
current radio buttons for breeding, non-breeding, and all filter the data based on the AtlasCache Safe Dates table. If species not in the table, breeding season = 5/1 to 10/30

**Comment by chene7** [comment]
Might be helpful for troubleshooting widget by adding these labels to the plot in blkcumhrfunc.r:
               "Total Breeding Hours: ", round(sum(blk.hr[,c(4,5,6,7,8,9)]),digits = 2),"\n",
               "Total Winter Hours: ", round(sum(blk.hr[,c(2,3,12,13)]),digits = 2)
