### ISSUE TITLE
Mongo to EBD format converter

### ISSUE THREAD

**Issue by nmtarr** [nmtarr/NCBA#9]
Function to run on records from mongo to make them match the EBD format.

**Comment by skaclmbr** [comment]
Looking over the to_ebd_format() function, I have a suggestion that might be more flexible - LMK what you think.

What if you load a csv file that is a crosswalk between the Mongo format and the ebd format (including data types). That way the function could load the file, roll through the passed dataset (that could have any combination of EBD and mongo fields), and replace with the correct version. This allows us to be flexible in what we want the column names to be. Plus, if we incorporate other functions from elsewhere that use different column names, we can easily add a column to the CSV file and convert. Thoughts?

Example:
MONGO, EBD, DT
"OBSERVATION_DATE", "observation_date", date
"SAMPLING_EVENT_IDENTIFIER", "sampling_event_identifier", string
"OBSERVATIONS.COMMON_NAME", "common_name", string
